swagger: 2.0
info:
  version: "0.0.1"
  title: Hello World App
# during local development, the host should point to your local machine
host: localhost
# basePath is prefixed to all requests. 
basePath: /
schemes:
  # consider removing http before pushing a production-grade app
  - http
  - https
# the format of a body expected from the client (Content-Type)
consumes:
  - application/json
# the format of the response to the client (Accepts)
produces:
  - application/json
x-volos-resources: {}
paths:
  /hello:
    x-swagger-router-controller: hello_world
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used to bind a127 logic to routes
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: HelloWorldResponse
        # responses generally fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
